repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

- repo: https://github.com/Calinou/pre-commit-luacheck
  rev: v1.0.0
  hooks:
    - id: luacheck

exclude: Libs
# TODO: Add auto-formatting with lua-format (see CI)
