name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes luarocks
        luarocks install --local busted
        luarocks install --local luacheck
        luarocks install --local luacov

    # - name: Check formatting
    #   run: |
    #     diff -q <(lua-format -c .lua-format GimmeTheLoot.lua) GimmeTheLoot.lua
    #     diff -q <(lua-format -c .lua-format spec/rolls_spec.lua) spec/rolls_spec.lua

    - name: Run linting
      run: |
        /home/runner/.luarocks/bin/luacheck --config .luacheckrc .

    - name: Run tests
      run: |
        /home/runner/.luarocks/bin/busted
        /home/runner/.luarocks/bin/busted --run exhaustive

    - name: Report coverage
      run: |
        /home/runner/.luarocks/bin/luacov GimmeTheLoot.lua
        cat luacov.report.out
